default:
  image: node:lts
  before_script:
    - npm install

stages:
  - deploy

pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  script:
    - npm run build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  only:
    - master
